pull_request_rules:
  - name: automatic merge develop -> master
    conditions:
      # pull request has label set by our create PR action
      - label=auto-pr
      - status-success=ci/circleci: build
    actions:
      merge:
        method: merge
