# prints GitHub event details for Pull Requests
name: Print PR event
on:
  pull_request
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo $GITHUB_EVENT
