# prints all GitHub events
name: Print event
on:
  pull_request
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo $GITHUB_EVENT
